spring.application.name=LibraryAPI
springdoc.swagger-ui.path=/swagger-ui.html
security.jwt.secret=${JWT_SECRET_BASE64}
security.jwt.access-token-ttl=PT15M

# TODO: Should be `validate` and app should use migration mechanism, such as Flyway or Liquibase
spring.jpa.hibernate.ddl-auto=update