spring.application.name=LibraryAPI
springdoc.swagger-ui.path=/swagger-ui.html

# TODO: Should be `validate` and app should use migration mechanism, such as Flyway or Liquibase
spring.jpa.hibernate.ddl-auto=update